dataSource:
  springboot:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.212.161:3406/springboot?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: abc@123